# Generated by Django 5.1.4 on 2024-12-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recepe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepe_name', models.CharField(max_length=100)),
                ('recepe_description', models.TextField()),
                ('recepe_image', models.ImageField(upload_to='recepe_image')),
            ],
        ),
    ]
